Repository fresha/api-tools, pull requests merged in 2023-03, with the labels that each got.

#128 client-fetch codegen passes action name to successCallback
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
  packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
Labels: enhancement

#133 Generate OpenAPI client types in a separate file
  packages/openapi-codegen-client-fetch/src/Generator.ts
  packages/openapi-codegen-client-fetch/src/context.ts
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
  packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts
  packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts
  packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts
  packages/openapi-codegen-client-fetch/src/parts/ResourceType.test.ts
  packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts
  packages/openapi-codegen-client-fetch/src/testHelpers.ts
Labels: enhancement

#134 Add JSDoc blocks to action functions, request and response types
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
  packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts
  packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts
  packages/openapi-codegen-client-fetch/src/parts/ResourceType.test.ts
  packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts
Labels: enhancement

#130 Implement generation of request formatters in client-fetch
  packages/openapi-codegen-client-fetch/src/Generator.ts
  packages/openapi-codegen-client-fetch/src/command.ts
  packages/openapi-codegen-client-fetch/src/context.ts
  packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts
  packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts
  packages/openapi-codegen-client-fetch/src/parts/NamedType.ts
  packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.test.ts
  packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.ts
  packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts
  packages/openapi-codegen-client-fetch/src/parts/index.ts
  packages/openapi-codegen-client-fetch/src/testHelpers.ts
  packages/openapi-model/src/3.0.3/model/Schema.ts
  packages/openapi-model/src/3.0.3/model/types.ts
Labels: enhancement

#135 Move yargs-related code to openapi-codegen-cli
  package-lock.json
  packages/openapi-codegen-cli/src/commands/client-fetch.ts
  packages/openapi-codegen-cli/src/commands/common.ts
  packages/openapi-codegen-cli/src/commands/docs-json-api.ts
  packages/openapi-codegen-cli/src/commands/server-elixir.ts
  packages/openapi-codegen-cli/src/commands/server-mock.ts
  packages/openapi-codegen-cli/src/commands/server-nestjs.ts
  packages/openapi-codegen-cli/src/index.ts
  packages/openapi-codegen-client-fetch/src/context.ts
  packages/openapi-codegen-client-fetch/src/index.ts
  packages/openapi-codegen-docs/src/context.ts
  packages/openapi-codegen-docs/src/index.ts
  packages/openapi-codegen-server-elixir/src/command.ts
  packages/openapi-codegen-server-elixir/src/context.ts
  packages/openapi-codegen-server-elixir/src/index.ts
  packages/openapi-codegen-server-mock/src/command.ts
  packages/openapi-codegen-server-mock/src/context.ts
  packages/openapi-codegen-server-mock/src/index.ts
  packages/openapi-codegen-server-nestjs/package.json
  packages/openapi-codegen-server-nestjs/src/command.ts
  packages/openapi-codegen-server-nestjs/src/context.ts
  packages/openapi-codegen-server-nestjs/src/index.ts
  packages/openapi-codegen-utils/src/context.ts
  packages/openapi-codegen-utils/src/index.ts
Labels: refactor

#140 Replace nested collections in openapi-model with methods
  packages/json-api-model/src/RelationshipSchema.test.ts
  packages/json-api-model/src/RelationshipSchema.ts
  packages/json-api-model/src/ResourceSchema.ts
  packages/json-api-model/src/SchemaRegistry.test.ts
  packages/json-api-model/src/SchemaRegistry.ts
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
  packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts
  packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts
  packages/openapi-codegen-client-fetch/src/parts/utils.test.ts
  packages/openapi-codegen-client-fetch/src/parts/utils.ts
  packages/openapi-codegen-docs/src/parts/Generator.ts
  packages/openapi-codegen-server-elixir/src/parts/Action.ts
  packages/openapi-codegen-server-elixir/src/parts/ResourceTestSuite.ts
  packages/openapi-codegen-server-nestjs/src/DTO.ts
  packages/openapi-codegen-server-nestjs/src/Generator.test.ts
  packages/openapi-codegen-utils/src/jsonapi.ts
  packages/openapi-codegen-utils/src/openapi.ts
  packages/openapi-diff/src/Differ.ts
  packages/openapi-lint/src/rules/oas3/noUnusedSharedComponents.ts
  packages/openapi-model/src/3.0.3/model/BasicNode.ts
  packages/openapi-model/src/3.0.3/model/Components.test.ts
  packages/openapi-model/src/3.0.3/model/Components.ts
  packages/openapi-model/src/3.0.3/model/Encoding.ts
  packages/openapi-model/src/3.0.3/model/OAuthFlow/OAuthAuthorisationCodeFlow.ts
  packages/openapi-model/src/3.0.3/model/OAuthFlow/OAuthClientCredentialsFlow.ts
  packages/openapi-model/src/3.0.3/model/OAuthFlow/OAuthFlowBase.test.ts
  packages/openapi-model/src/3.0.3/model/OAuthFlow/OAuthFlowBase.ts
  packages/openapi-model/src/3.0.3/model/OAuthFlow/OAuthImplicitFlow.ts
  packages/openapi-model/src/3.0.3/model/OAuthFlow/OAuthPasswordFlow.ts
  packages/openapi-model/src/3.0.3/model/OpenAPI.ts
  packages/openapi-model/src/3.0.3/model/OpenAPIReader.test.ts
  packages/openapi-model/src/3.0.3/model/OpenAPIReader.ts
  packages/openapi-model/src/3.0.3/model/OpenAPIWriter.test.ts
  packages/openapi-model/src/3.0.3/model/OpenAPIWriter.ts
  packages/openapi-model/src/3.0.3/model/Operation.test.ts
  packages/openapi-model/src/3.0.3/model/Operation.ts
  packages/openapi-model/src/3.0.3/model/Response.ts
  packages/openapi-model/src/3.0.3/model/Schema.test.ts
  packages/openapi-model/src/3.0.3/model/Schema.ts
  packages/openapi-model/src/3.0.3/model/SecurityScheme/APIKeySecurityScheme.ts
  packages/openapi-model/src/3.0.3/model/SecurityScheme/HTTPSecurityScheme.ts
  packages/openapi-model/src/3.0.3/model/SecurityScheme/OAuth2SecurityScheme.ts
  packages/openapi-model/src/3.0.3/model/SecurityScheme/OpenIdConnectSecurityScheme.ts
  packages/openapi-model/src/3.0.3/model/SecurityScheme/SecuritySchemeBase.ts
  packages/openapi-model/src/3.0.3/model/Tag.ts
  packages/openapi-model/src/3.0.3/model/types.ts
Labels: refactor

#144 Allow optional header parameters
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
  packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
Labels: bug
